### ISSUE TITLE
Location of "executable"?

### ISSUE THREAD

**Issue by b-morgan** [Flachdachs/ArkSaveAnalyzer#1]
This may be a stupid question but a lot of github open source projects including this one don't seem to have a pointer and/or instructions point to an "executable" file. If there is a generic "github" answer please point me to it. Otherwise, a Wiki entry or something in the readme would be fantastic.

**Comment by Flachdachs** [comment]
Releases are not planned. You will need Visual Studio or an equivalent IDE to compile it.
