### ISSUE TITLE
Needs Map info for Crystal Isles,Valguero and Genesis

### ISSUE THREAD

**Issue by moozoo64** [Flachdachs/ArkSaveAnalyzer#2]
I can do this myself I you tell me how.
I have it partially working with Crystal Isles. I copied Ragnarok's values.  The locations are out by a smallish amount.
My plan is to put a tame on each of the obelisks and play with the number till the tame locations match the known obelisk locations.
But... is there a better way.

Also I'd like to see a Map for where the Filtered Wild dinos are.

**Comment by Flachdachs** [comment]
7e479d2
