### ISSUE TITLE
An item with the same key has already been added - displayed

### ISSUE THREAD

**Issue by anewhomegw2** [Flachdachs/ArkSaveAnalyzer#3]
When loading the structures list (scorched earth save) - get the error message and no structures appear on the list.
@Flachdachs 

When trying to load 'The Island' also get this message and the save is not parsed.

Added ZIP files for the save games to assist with debugging.
[ARK Testing.zip](https://github.com/Flachdachs/ArkSaveAnalyzer/files/5880517/ARK.Testing.zip)

**Comment by Flachdachs** [comment]
Fixed in fd90a46
